apps/user/urls.py
# -*- coding:utf-8 -*-
__author__ = 'qing.cai@horizon.ai'

from django.urls import path, re_path, include
from user.views import (LoginView, LogoutView, UserListView, UserCreateView, UserOpHistoryLog)


urlpatterns = [
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),
    re_path(r'^user/$', UserListView.as_view(), name='user_list'),
    re_path(r'^user/create/$', UserCreateView.as_view(), name='user_add'),
    re_path(r'^log/user/$', UserOpHistoryLog.as_view(), name='log-user')
]

apps/utils/django-celery-beat-master/t/proj/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

autocronjob/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework.documentation import include_docs_urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.static import serve

from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token
from cronjob.api import MailAddressViewSet, WebhookUrlViewSet, IndexChartData
from user.api import UserProfileViewSet
from log.api import OpLogViewSet

router = routers.DefaultRouter()
# 用户接口
router.register(r'user', UserProfileViewSet, base_name="user")
# 审计日志接口(审计内容待补充)
router.register(r'log', OpLogViewSet, base_name='log')
# mail接口
router.register(r'mail', MailAddressViewSet, base_name='mail')
# webhook接口
router.register(r'webhook', WebhookUrlViewSet, base_name='webhook')

urlpatterns = [
    path('admin/', admin.site.urls),
    # 应用接口
    path('api/', include(router.urls)),
    # 非api接口
    path('', include('user.urls')),
    path('', include('cronjob.urls')),
    path('', include('log.urls')),
    # index数据接口
    re_path(r'^api/index_chart_data/$', IndexChartData.as_view(), name='index_chart_data'),
    # drf登录认证
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # jwt认证
    re_path(r'^api/token-auth/$', obtain_jwt_token),
    # api文档
    re_path(r'^docs/', include_docs_urls(title="autocronjob")),
]

apps/log/models.py
# -*- coding:utf-8 -*-

from django.db import models


class OperationLog(models.Model):
    """
    弃用
    """
    op_user = models.CharField(max_length=20, null=True)
    op_user_ip = models.CharField(max_length=200, null=True)
    op_msg = models.CharField(max_length=50)
    op_object = models.CharField(max_length=200)
    op_time = models.DateTimeField(auto_now=True)
    is_success = models.BooleanField()
    op_failed_msg = models.CharField(max_length=2000, null=True, blank=True)

    class Meta:
        verbose_name = "操作日志"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.op_user

#
# from simple_history import register
# from simple_history.models import HistoricalRecords
# from django_celery_beat.models import IntervalSchedule, PeriodicTask
#
#
# # 这种方式记录第三方组件，默认只能读取到一条历史差异，后面可以在仔细实验一下
# register(IntervalSchedule)
# register(PeriodicTask)


class HistoryLogRecords(models.Model):
    """
    当前使用
    """
    op_user = models.CharField(max_length=20, null=True)
    op_msg = models.TextField()
    op_type = models.CharField(max_length=30)
    op_time = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "操作日志"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.op_user

apps/user/models.py
# -*- coding:utf-8 -*-

from django.db import models
from django.contrib.auth.models import AbstractUser
from simple_history.models import HistoricalRecords


class UserProfile(AbstractUser):
    """
    userprofile
    """
    name = models.CharField(max_length=30, null=True, blank=True, verbose_name="姓名")
    email = models.EmailField(max_length=100, null=True, blank=True, verbose_name="邮箱")
    # changed_by = models.ForeignKey('user.UserProfile', null=True, blank=True, on_delete=models.SET_NULL, )
    history = HistoricalRecords(excluded_fields=['first_name', 'is_staff', 'last_name', 'date_joined', 'last_login'])

    class Meta:
        verbose_name = "用户"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username.__str__()

apps/user/forms.py
# -*- coding:utf-8 -*-
__author__ = 'qing.cai@horizon.ai'

from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)

apps/user/views.py
# -*- coding:utf-8 -*-

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import AccessMixin
from django.shortcuts import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic.edit import FormView
from django.contrib.auth import authenticate, login
from django.urls import reverse
from django.shortcuts import render as my_render
from django.views.generic import TemplateView, ListView, View

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import HttpResponse
from django.contrib import auth
from .forms import LoginForm
from .models import UserProfile
from utils.admin_permission import superpermission
from django.contrib.auth import get_user_model
import json
import datetime

User = get_user_model()


class LoginRequiredMixin(AccessMixin):

    @method_decorator(login_required(redirect_field_name='next', login_url='/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class LoginView(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    redirect_field_name = 'next'

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs.update({
            'next': self.request.GET.get('next', '')
        })
        return kwargs

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('index'))
        else:
            return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        login_form = self.get_form()
        if login_form.is_valid():
            user_name = login_form.cleaned_data['username']
            pass_word = login_form.cleaned_data['password']
            if User.objects.filter(username=user_name).exists():
                next = request.POST.get('next', '')
                user = authenticate(username=user_name, password=pass_word)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        request.session.clear_expired()
                        if next:
                            return HttpResponseRedirect(next)
                        else:
                            return HttpResponseRedirect(reverse('index'))
                    else:
                        return my_render(request, "login.html", {"msq": "用户未激活，请联系管理！"})
                else:
                    return my_render(request, "login.html", {"msq": "用户未激活或密码错误，请联系管理员！"})
            else:
                return my_render(request, "login.html", {"msq": "用户不存在，请确定用户名后再次登录！"})
        else:
            return my_render(request, "login.html", {"msq": "用户验证失败，请联系管理员！", "login_form": login_form})


class LogoutView(View):
    def get(self, request):
        auth.logout(request)
        return HttpResponseRedirect("/login/")


@method_decorator(superpermission, name='dispatch')
class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = "user_list.html"
    context_object_name = "user_info"


@method_decorator(superpermission, name='dispatch')
class UserCreateView(LoginRequiredMixin, TemplateView):
    template_name = "user_create.html"


class UserOpHistoryLog(LoginRequiredMixin, View):
    """
    非api 日志分页显示
    """
    def get(self, request):
        start_time = (datetime.datetime.now() - datetime.timedelta(days=30)).strftime('%Y-%m-%d %H:%M:%S')
        end_time = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        return my_render(request, 'user_history_op_log.html', locals())

    def post(self, request):
        dataTable = {}
        search_data = {}
        aodata = json.loads(request.POST.get("aodata"))
        for item in aodata:
            if item['name'] == "sEcho":
                sEcho = int(item['value'])  # 客户端发送的标识
            if item['name'] == "iDisplayStart":
                iDisplayStart = int(item['value'])  # 起始索引
            if item['name'] == "iDisplayLength":
                iDisplayLength = int(item['value'])  # 每页显示的行数
            # if item['name'] == 'op_user':
            #     search_data['op_user'] = item['value']
            if item['name'] == "search_time":
                search_data['history_date__range'] = item['value']
        if search_data:
            all_data_list = User.history.filter(**search_data).order_by('-history_date')
        else:
            all_data_list = User.history.all().order_by('-history_date')
        resultLength = all_data_list.count()
        # 对list进行分页
        paginator = Paginator(all_data_list, iDisplayLength)
        # 把数据分成10个一页。
        try:
            all_data_list = paginator.page(iDisplayStart / 10 + 1)
        # 请求页数错误
        except PageNotAnInteger:
            all_data_list = paginator.page(1)
        except EmptyPage:
            all_data_list = paginator.page(paginator.num_pages)
        data = []

        # ope_type = {'~': 'update', '+': 'create', '-': 'delete'}
        # new_record, old_record, *_ = all_data_list
        # # print(User.history.all().count())
        # delta = new_record.diff_against(old_record)
        # for change in iter(delta.changes):
        #     print("{} changed from {} to {}".format(change.field, change.old, change.new))
        #     row = {"op_user": User.objects.get(id=new_record.history_user_id).username,
        #            "op_msg": "{} changed from {} to {}".format(change.field, change.old, change.new),
        #            "op_object": ope_type[new_record.history_type],
        #            "op_time": new_record.history_date.strftime('%Y-%m-%d %H:%M:%S')}
        #
        #     data.append(row)
        # 对最终的数据进行倒序排序
        data = sorted(data, key=lambda item: item['op_time'], reverse=True)
        dataTable['iTotalRecords'] = resultLength  # 数据总条数
        dataTable['sEcho'] = sEcho + 1
        dataTable['iTotalDisplayRecords'] = resultLength  # 显示的条数
        dataTable['aaData'] = data
        return HttpResponse(json.dumps(dataTable, ensure_ascii=False))

apps/user/templates/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>autocronjob | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static '/autocronjob/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static '/autocronjob/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static '/autocronjob/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static '/plugins/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="../../autocronjob/js/html5shiv.min.js"></script>
  <script src="../../autocronjob/js/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href=""><b>auto</b>cronjob</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>



    {% if login_form.errors %}
      <div class="alert alert-warning alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <span><i class="icon fa fa-warning"></i> <b>{% for key,error in login_form.errors.items %}{{ key }}:{{ error }}{% endfor %}</b></span>
      </div>
    {% elif msq %}
      <div class="alert alert-warning alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <span><i class="icon fa fa-warning"></i> <b>{{ msq }}</b></span>
      </div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">{% csrf_token %}
      <div class="form-group has-feedback">

        <input type="text" class="form-control" placeholder="Username" name="username">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
          <input type="password" class="form-control" placeholder="Password" name="password">
          <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div>
        <!-- /.col -->
      </div>
        <input name="next" type="hidden" value="{{ next }}"/>
    </form>

{#    <a href="#">I forgot my password</a><br>#}

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 2.2.3 -->
<script src="{% static '/plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static '/plugins/iCheck/icheck.min.js' %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>
</body>
</html>

apps/user/templates/user_create.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'plugins/json-forms/css/brutusin-json-forms.css' %}">
{% endblock %}
{% block content %}

<div class="col-md-12">
    <!-- BEGIN EXAMPLE TABLE PORTLET-->
    <div class="box box-success">
        <div class="box-header with-border">
            <div class="caption">
                <button class="btn btn-primary" onclick="window.location.href = '{% url 'user_list' %}'">
                    返回
                </button>
            </div>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                        class="fa fa-minus"></i>
                </button>
                <div class="btn-group">
                    <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-wrench"></i></button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">操作</a></li>
                        <li><a href="#">另一个操作</a></li>
                        <li><a href="#">其他</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </div>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-lg-10">
                    <div class="content float-e-margins">
                        <div class="content">
                            <form class="form-horizontal nice-validator n-yellow form" id="table" method="post" novalidate="novalidate">
                                {% csrf_token %}
                                <div id='user_container' class="table"></div>
                                <div class="col-sm-4 col-sm-offset-5">
                                    <button type="submit" id="submit" class="btn btn-primary pull-center">
                                        保存
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END EXAMPLE TABLE PORTLET-->
</div>


{% endblock %}
{% block js %}
<script>
  $('#page_header').text('用户管理');
  $('#page_header_descript').text('添加用户');
</script>
    <!-- DataTables -->
    <script src="{% static 'plugins/json-forms/js/brutusin-json-forms.js' %} "></script>
    <script src="{% static 'plugins/json-forms/js/brutusin-json-forms-bootstrap.js' %} "></script>
<script type="application/javascript">
    var schema = {
        "type": "object",
        "properties": {
            "username": {
                "type": "string",
                'title': "用户名",
                "description": "用户名",
                "required": true,
                "maxLength": 140
            },
            "name": {
                "type": "string",
                "title": "姓名",
                "description": "姓名",
                "required": true
                },
            "password": {
                "type": "string",
                "format": "password",
                "title": "密码",
                "description": "密码",
                "required": true
                },
            "password1": {
                "type": "string",
                "format": "password",
                "title": "确认密码",
                "description": "确认密码",
                "required": true
                },
            "email": {
                "type": "string",
                "format": "email",
                "title": "邮箱",
                "description": "邮箱",
                "required": true
                },
            "is_active": {
                "type": "boolean",
                "title": "启用",
                "description": "启用",
                "default": true,
                "properties": {
                    "enabled": {
                        "type": "boolean",
                        "title": "启用"
                    },
                },
                "required": [
                    "enabled"
                ]
            },
            "is_superuser": {
                "type": "boolean",
                "title": "管理员",
                "description": "角色是否为管理员",
                "default": false,
                "properties": {
                    "enabled": {
                        "type": "boolean",
                        "title": "启用"
                    }
                },
                "required": [
                    "enabled"
                ]
            }

            }
        };

var BrutusinForms = brutusin["json-forms"];
BrutusinForms.bootstrap.addFormatDecorator("password", "password");
BrutusinForms.bootstrap.addFormatDecorator("password1", "password");
BrutusinForms.bootstrap.addFormatDecorator("email", "email");
var bf = BrutusinForms.create(schema);
var container = document.getElementById('user_container');
bf.render(container, null);


$("#submit").on('click', function (e) {
    e.preventDefault();
    var jsondata = bf.getData();
    if (jsondata.password === jsondata.password1) {
        if (bf.validate()) {
            $.ajax({
                type: "POST",
                url: "{% url 'user-list' %}",
                data: JSON.stringify(jsondata, null, 4),
                dataType: "json",
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                },
                success: function (data) {
                    toastr["success"]("username "+jsondata.username+" "+data.message);
                    setTimeout(function () {
                        window.location.href='{% url 'user_list' %}';
                    },2000);
                },
                failure: function (errMsg) {
                    toastr["error"](errMsg);
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    toastr["error"]("username "+jsondata.username+" "+JSON.parse(XMLHttpRequest.responseText).message);
                }
            });
        }
    } else {
        toastr["error"]("输入的密码不一致，请重新输入。")
    }
});

</script>
{% endblock %}

apps/user/templates/user_history_op_log.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'plugins/bootstrap-select/css/bootstrap-select.css' %} ">
<link rel="stylesheet" href="{% static 'plugins/json-forms/css/brutusin-json-forms.css' %} ">
<!-- DataTables css -->
<link rel="stylesheet" href="{% static '/plugins/datatables/dataTables.bootstrap.css' %}">
<link rel="stylesheet" href="{% static "plugins/json-view/jquery.jsonview.min.css" %}">
<link rel="stylesheet" href="{% static "plugins/datepicker/datepicker3.css" %}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{% static "plugins/daterangepicker/daterangepicker.css" %}">
{% endblock %}
{% block content %}
<div class="col-xs-12">
  <div class="box">
      <div class="box-body">
        <form class="form-inline">
            <div class="form-group form-group-sm">
                <label for="task_name">操作用户名:</label>
                <input  type="text" style="width:200px;margin-right: 30px" class="form-control input-sm" placeholder="不支持模糊搜索" id="id_op_user" name="op_user">
                <label for="id_start_time">开始时间:</label>
                <input style="margin-right: 30px" class="form-control input-sm datetime" id="id_start_time" maxlength="" name="start_time" placeholder="Start Time" required="required" value="{{ start_time }}" type="text">
                <label for="id_end_time">结束时间:</label>
                <input style="margin-right: 30px" class="form-control input-sm datetime" id="id_end_time" maxlength="" name="end_time" placeholder="End Time" required="required" value="{{ end_time }}" type="text">
            </div>
            <div class="form-group form-group-sm">
                <a class="btn btn-block btn-primary btn-sm" id="query" onclick="oplog_search()">搜索</a>
            </div>
        </form>
      </div>
    <!-- /.box-body -->
  </div>
  <div class="box">
    <div class="box-body">
        <table class="table table-bordered table-striped table-hover" id="operationloglist" style="width: 100%">
        </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
</div>
<!-- /.col -->
{% endblock %}
{% block js %}
<script>
  $('#page_header').text('日志审计');
  $('#page_header_descript').text('操作平台审计');
</script>
<!-- daterangepicker -->
<script src="{% static "autocronjob/js/moment.min.js" %}"></script>
<script src="{% static "plugins/daterangepicker/daterangepicker.js" %}"></script>
<!-- datepicker -->
<script src="{% static "plugins/datepicker/bootstrap-datepicker.js" %}"></script>
<script src="{% static 'plugins/markdown/markdown.js' %} "></script>
<script src="{% static 'plugins/bootstrap-select/js/bootstrap-select.js' %} "></script>
<!-- DataTables -->
<script src="{% static '/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static '/plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
{#<script src="{% static 'plugins/daterangepicker/moment.js' %}"></script>#}
<script type="text/javascript">
	  $(function () {
	  $('.datetime').daterangepicker({
	  timePicker: true,
	  timePickerIncrement: 1,
	  format: 'YYYY-MM-DD HH:mm:ss',
		timePickerSeconds:true,
		autoApply:true,
		singleDatePicker:true,
		timePicker24Hour:true,
		clearStatus:false,
		autoUpdateInput: false,
		locale: {
			"format": 'YYYY-MM-DD HH:mm:ss'
		}
	  });

		$('.datetime').on('apply.daterangepicker', function(ev, picker) {
			$(this).val(picker.startDate.format('YYYY-MM-DD HH:mm:ss'));
		});

		$('.datetime').on('cancel.daterangepicker', function(ev, picker) {
		$(this).val('');
		});
	  });
</script>

<script>
var table;
function oplog_search() {
    if ($('input[name=start_time]').val().length !== 0 && $('input[name=end_time]').val().length !== 0) {
        if ($('input[name=start_time]').val() > $('input[name=end_time]').val()) {
            toastr["error"]('开始时间不能大于结束时间，请重新选择!');
        } else {
            table.clear();
            table.draw();
        }
    } else {
        toastr["error"]('时间不能为空，请重新选择!');
    }
}

// table初始化方法
function initDataTable(urlParam, columnsParam) {
    return {
            sPaginationType: "full_numbers", //分页风格，full_number会把所有页码显示出来
            searching: false,//搜索
            ordering: false,//是否启用排序
            bProcessing: true, //是否显示加载
            sAjaxSource: urlParam, //请求资源路径
            serverSide: true, //开启服务器处理模式
            /*
             使用ajax，在服务端处理数据
             sSource:即是"sAjaxSource"
             aoData:要传递到服务端的参数
             fnCallback:处理返回数据的回调函数
             */
            fnServerData: function (sSource, aoData, fnCallback) {
                var op_user = $('#id_op_user').val();
                if (op_user.length  !== 0) {
                    aoData.push({ "name": "op_user", "value": op_user});
                }
                aoData.push({"name": "search_time", "value": [$('input[name=start_time]').val(), $('input[name=end_time]').val()]});
                $.ajax({
                    'type': 'POST',
                    "url": sSource,
                    "dataType": "json",
                    "data": {"aodata": JSON.stringify(aoData)},
                    "success": function (resp) {
                        fnCallback(resp);
                    }
                });
            },
            "oLanguage": {//语言设置
                "sLengthMenu": '<select class="form-control" style="width:150px">'
                + '<option value="10"  selected>每页10条</option>'
                + '<option value="20">每页20条</option>'
                + '<option value="50">每页50条</option>'
                + '<option value="100">每页100条</option>'
                + '</select>',
                "sProcessing": "处理中...",
                "sZeroRecords": "没有匹配结果",
                "sInfo": "Showing _START_ to _END_ of _TOTAL_ entries",
                "sInfoEmpty": "没有数据",
                "sInfoFiltered": "(获取 _MAX_ 项结果)",
                "sInfoPostFix": "",
                "sSearch": "搜索:",
                "sUrl": "",
                "sEmptyTable": "No data available in table",
                "sLoadingRecords": "loading...",
                "sInfoThousands": ",",
                "oPaginate": {
                    "sFirst": "Home",
                    "sPrevious": "Previous",
                    "sNext": "Next",
                    "sLast": "End"
                }
            },
{#            "bProcessing": true, //开启读取服务器数据时显示正在加载中……特别是大数据量的时候，开启此功能比较好#}
            "bServerSide": true, //开启服务器模式，使用服务器端处理配置datatable。
            // 注意：sAjaxSource参数也必须被给予为了给datatable源代码来获取所需的数据对于每个画。
            // 这个翻译有点别扭。开启此模式后，你对datatables的每个操作 每页显示多少条记录、下一页、上一页、排序（表头）、搜索，这些都会传给服务器相应的值。
            "columns": columnsParam
    }
}

var urlParam = "{% url 'log-user' %}";
var columnsParam = [
    {title: "操作用户名", data: "op_user"},
    {
        title: "操作时间",
        data: "op_time",
        "render": function (data, type, full, meta) {
            return moment.utc(data).local().format("YYYY-MM-DD HH:mm:ss");

        }
    },
    {title: "操作内容", data: "op_msg"},
    {title: "操作对象", data: "op_object"},
    {#{#}
    {#    title: "操作失败原因",#}
    {#    data: "op_failed_msg",#}
    {#    "render": function (data, type, full, meta) {#}
    {#        if (data === null || data === ''){#}
    {#            return '-'#}
    {#        } else  {#}
    {#            return data#}
    {#        }#}
    {##}
    {#    }#}
    {#}#}
    ];

$(function () {
    table = $('#operationloglist').DataTable(
        initDataTable(urlParam, columnsParam)
    );
});
</script>
{% endblock %}